name: flutter_date_difference
description: Calculates the difference between two dates. It allows customization.
version: 1.0.1
homepage: https://erbasaran.com
repository: https://github.com/erbasaran/flutter_date_difference
issue_tracker: https://github.com/erbasaran/flutter_date_difference/issues

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
